apiVersion: v1
kind: Pod
metadata:
    name: pod-volume
spec:
    containers:
    - name: app1
      image: supergiantkir/animals:bear
      volumeMounts:
      - name: app-storage
        mountPath: /storage
    - name: app2
      image: supergiantkir/animals:moose
      volumeMounts:
      - name: app-storage
        mountPath: /storage
    volumes:
    - name: app-storage
      emptyDir: {}
